#!/bin/sh
if ! grep ion /etc/shells >/dev/null; then
	echo $(BINARY) >> /etc/shells;
else
	shell=$(shell grep ion /etc/shells);
	if [ $$shell != $(BINARY) ]; then
		before=$$(echo $$shell | sed 's/\//\\\//g');
		after=$$(echo $(BINARY) | sed 's/\//\\\//g');
		sed -i -e "s/$$before/$$after/g" /etc/shells;
	fi
fi

