#!/bin/sh
BINARY="/usr/bin/ion"
if ! grep ion /etc/shells >/dev/null; then
    echo ${BINARY} >> /etc/shells
else
    shell=$(grep ion /etc/shells)
    if [ "$shell" != "${BINARY}" ]; then
        sed -i -e "s#$shell#${BINARY}#g" /etc/shells
    fi
fi
